### ISSUE TITLE
"Verify the data was loaded correctly" returns an error

### ISSUE THREAD

**Issue by CharlineJnnt** [sfu-ireceptor/turnkey-service-php#32]
Hi, 

After installing the iReceptor Turnkey v4 on my virtual machine and updated the test data provided by your github (according to the new AIR Standard updates), I loaded them following the procedure. 

However, in the 3rd step when I executed the command : 
scripts/verify_dataload.sh PRJNA330606 test_data PRJNA330606_Wang_1_sample_metadata.csv mixcr /tmp

I got this error: 

```
INFO: Starting run at:  2022-11-10_10-30-19
INFO: Generate facet queries
ERROR: Server could not fullfil the request to http://ireceptor-api//airr/v1/repertoire
ERROR: Error code = 308, Message =  b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>308 Permanent Redirect</title>\n</head><body>\n<h1>Permanent Redirect</h1>\n<p>The document has moved <a href="https://ireceptor-api/airr/v1/repertoire">here</a>.</p>\n<hr>\n<address>Apache/2.4.54 (Debian) Server at ireceptor-api Port 80</address>\n</body></html>\n'
ERROR: Query failed to http://ireceptor-api//airr/v1/repertoire
ERROR: Could not generate queries correctly.
```

 Which I managed to fix it by replacing the path "http://ireceptor-api/" (line 75) by "https://localhost" in verify_dataload.sh script. 

Please let me know if this solution is correct.

**Comment by bcorrie** [comment]
Hi @CharlineJnnt 

Thanks for pointing this out. On the newest version of the iReceptor Turnkey, we enable https by default with a self-signed SSL certificate. It looks to me like perhaps our `verify_dataload.sh` script has not been updated to reflect this change. That is likely why you are getting this error and making the https: change works.

We will file an internal bug report to get this fixed.

Another option that should solve this problem is to run the `disable_https.sh` script, which will disable https (as the name implies) and then the `verify_dataload.sh` script should work. You could do this temporarily to run the `verify_dataload.sh` script and then run `enable_https.sh` afterwards to turn it back on for normal use.
